# Generated by Django 5.0.6 on 2026-05-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_add_teaching_assignment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
