# Generated by Django 5.0.6 on 2026-05-05 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDropRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_code', models.CharField(blank=True, max_length=20)),
                ('request_type', models.CharField(choices=[('Add', 'Add'), ('Drop', 'Drop')], max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_add_drops', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_drop_requests', to='students.student')),
            ],
            options={
                'db_table': 'add_drop_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_code', models.CharField(blank=True, max_length=20)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('choice', models.CharField(choices=[('Cafe', 'Cafe'), ('Non-Cafe', 'Non-Cafe')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafeteria_requests', to='academics.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cafeteria', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_requests', to='students.student')),
            ],
            options={
                'db_table': 'cafeteria_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
