# Generated by Django 5.0.6 on 2026-05-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('qualification', models.CharField(blank=True, choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD'), ('BA', 'BA'), ('MA', 'MA'), ('Other', 'Other')], max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('office_room', models.CharField(blank=True, max_length=50)),
                ('office_hours', models.CharField(blank=True, max_length=100)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_profiles',
            },
        ),
    ]
