# Generated by Django 5.0.6 on 2026-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_make_teacher_id_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_semester',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
