# Generated by Django 5.0.6 on 2026-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='Wollo University', max_length=200)),
                ('campus_name', models.CharField(default='Kombolcha Campus', max_length=200)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('current_semester', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'university_settings',
            },
        ),
    ]
